spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Tiger@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
